### PR TITLE
WIP: Edit the text of the top button in ImageCapture - closes issue #29

### PR DESCRIPTION
**Pull request by letakeane**
## What's this PR do?

_Adjust the text of the top button in ImageCapture.js to read 'start camera' (to match the lowercase aesthetic of the app as a whole) instead the less clear 'Start video'._

## Where should the reviewer start?

_Does this text make more sense? The user doesn't necessarily think of this as a video; it's just the camera. I also hope to clarify that the user must hit the 'start camera' button before the 'take picture' button._

## Screenshots (if appropriate)
Before:
before

After:
after

### CODE REVIEW

**Comment by JohnBinning** [comment]
That definitely looks better.  It's a bit easier on the eyes with the lowercase.  I feel that the border is a bit friendlier as well.

**Comment by Adamj1232** [comment]
That makes a lot more sense with 'camera' in the button. I would be interested to see how all letters in the button look in caps. Might work, might not....looks good as is though!

**Comment by Jeff-Duke** [comment]
I wonder about replacing 'start camera' with an svg of a camera?  it's a pretty common pattern in video chat apps, your smart phone etc.  also you might disable the 'take picture' button and have it only enable once the camera has successfully been started.

**Comment by letakeane** [comment]
@Jeff-Duke Conditionally rendering the different buttons in the same location is DEFINITELY my plan; I'll create a new Issue for it :)

**Pull request merged**
