### PR TITLE
Edit face oval to match comp more closely - closes Issue #30

### PR DESCRIPTION
**Pull request by letakeane**
## What's this PR do?

_Edit the face oval in ImageCapture to more closely match the original comp and improve UI._

## Where should the reviewer start?

_Let me know if this improves UX/UI or is more intuitive._

## Screenshots
Original design (please ignore the black background - the difference to focus on is the oval):
before

Updated design:
after

And with the webcam running:
after with video

### CODE REVIEW

**Comment by cbandrow** [comment]
I think the oval looks good! Much more understandable for a user to know where they should put their face.

**Comment by Adamj1232** [comment]
I totally agree with Chris, the oval looks a lot better and makes for a lot smoother look throughout the UI

**Comment by cjorda15** [comment]
The oval certainly makes a difference. I want to put my face in it now compared to scary ants lines around me

**Comment by Jeff-Duke** [comment]
not sure if you're worried about mobile responsive etc but the `<article>` wrapping the video area is sized relative to the viewport.  when the viewport shrinks to a certain point the buttons and the face oval get really misaligned. 
screen shot 2017-06-06 at 9 33 10 am


If you change your styling on `.image-capture` from `width: 30vw` to something fixed like `min-width: 320px` your canvas, face oval and buttons will all look correct and be properly aligned at all screen widths.  you can use media queries to reorganize the rest of the page for a mobile view if you want to go down that route.

**Comment by letakeane** [comment]
@Jeff-Duke Yeah, the responsive is not in place. I think I'll wait until after Demo Night; I do want to make it fully responsive and available for mobile!

**Pull request merged**
